package com.fadybassem.domain.model

data class Movie(
    var adult: Boolean? = null,
    var backdropPath: String? = null,
    var belongsToCollection: BelongsToCollection? = BelongsToCollection(),
    var budget: Int? = null,
    var genreIds: ArrayList<Int> = arrayListOf(),
    var genres: ArrayList<Genres> = arrayListOf(),
    var genreNames: String? = null,
    var homepage: String? = null,
    var id: Int? = null,
    var imdbId: String? = null,
    var originCountry: ArrayList<String> = arrayListOf(),
    var originalLanguage: String? = null,
    var originalTitle: String? = null,
    var overview: String? = null,
    var popularity: Double? = null,
    var posterPath: String? = null,
    var productionCompanies: ArrayList<ProductionCompanies> = arrayListOf(),
    var productionCountries: ArrayList<ProductionCountries> = arrayListOf(),
    var releaseDate: String? = null,
    var revenue: Int? = null,
    var runtime: Int? = null,
    var spokenLanguages: ArrayList<SpokenLanguages> = arrayListOf(),
    var status: String? = null,
    var tagline: String? = null,
    var title: String? = null,
    var video: Boolean? = null,
    var voteAverage: Double? = null,
    var voteCount: Int? = null,
)